version: "3.8"

services:
  nginx:
    image: changc42/private:portfolio_nginx
    container_name: my_nginx
    ports:
      - 80:80
  portfolio:
    image: changc42/private:portfolio
    container_name: portfolio
  givmonies:
    image: changc42/private:giv_monies
    container_name: givmonies
# dev
# version: "3.8"

# services:
#   nginx:
#     image: nginx_image
#     container_name: my_nginx
#     ports:
#       - 3000:80
#   portfolio:
#     image: changc42/private:portfolio
#     container_name: portfolio
#   givmonies:
#     image: changc42/private:giv_monies
#     container_name: givmonies
