version: "3.0"

services:
  portfolio_nginx:
    image: changc42/private:portfolio_nginx
    container_name: portfolio_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - portfolio_nginx
    command: certificates
      # certonly --webroot --webroot-path=/var/www/html --email changc42@gmail.com --agree-tos --no-eff-email --force-renewal -d caleb.directory  -d www.caleb.directory -d portfolio.caleb.directory -d calculator.caleb.directory -d pokemonwar.caleb.directory -d dragndrop.caleb.directory -d givmonies.caleb.directory
  portfolio:
    image: changc42/private:portfolio
    container_name: portfolio
  givmonies:
    image: changc42/private:giv_monies
    container_name: givmonies
  calculator:
    image: changc42/private:calculator
    container_name: calculator
  dragndrop:
    image: changc42/private:dragndrop
    container_name: dragndrop
  pokemonwar:
    image: changc42/private:pokemonwar
    container_name: pokemonwar
    
volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /webroot
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /dhparam
      o: bind
# dev
# version: "3.8"

# services:
#   nginx:
#     image: nginx_image
#     container_name: my_nginx
#     ports:
#       - 3000:80
#   portfolio:
#     image: changc42/private:portfolio
#     container_name: portfolio
#   givmonies:
#     image: changc42/private:giv_monies
#     container_name: givmonies
