version: "3.0"

services:
  portfolio_nginx:
    image: changc42/private:portfolio_nginx
    container_name: portfolio_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - portfolio_nginx
    command:
      certonly --webroot --webroot-path=/var/www/html --email changc42@gmail.com --agree-tos --no-eff-email --force-renewal -d caleb.directory  -d www.caleb.directory -d portfolio.caleb.directory -d calculator.caleb.directory -d pokemonwar.caleb.directory -d dragndrop.caleb.directory -d givmonies.caleb.directory -d springbootreact.caleb.directory
      # certificates
  portfolio:
    image: changc42/private:portfolio
    container_name: portfolio
  givmonies:
    image: changc42/private:giv_monies
    container_name: givmonies
  calculator:
    image: changc42/private:calculator
    container_name: calculator
  dragndrop:
    image: changc42/private:dragndrop
    container_name: dragndrop
  pokemonwar:
    image: changc42/private:pokemonwar
    container_name: pokemonwar

  spring_boot_react:
    image: changc42/private:spring_boot_react
    depends_on:
      - sqldb_for_spring_boot_react
  sqldb_for_spring_boot_react:
    image: mysql
    container_name: sqldb_for_spring_boot_react
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: test_db
      MYSQL_USER: shopping
      MYSQL_PASSWORD: 12345678
    restart: always

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /webroot
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /dhparam
      o: bind
# dev
# version: "3.8"

# services:
#   nginx:
#     image: nginx_image
#     container_name: my_nginx
#     ports:
#       - 3000:80
#   portfolio:
#     image: changc42/private:portfolio
#     container_name: portfolio
#   givmonies:
#     image: changc42/private:giv_monies
#     container_name: givmonies
